'''
Created on Oct 28, 2011

@author: t22cf3p
'''
from xml.dom import minidom
import sys

if __name__ == '__main__':
    pass

if sys.argv.__len__() == 1:
    print "usage: "+sys.argv[0]+" [filetoprocess]"
    sys.exit(1);
    
fileName = str(sys.argv[1])

lookup=open(fileName,"r")
ucmUpdates = open(fileName.strip(".xml")+"Updates.xml","w+")

header="""<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<!DOCTYPE data [
    <!ELEMENT data (sql+)>
    <!ELEMENT sql EMPTY>
    <!ATTLIST sql
    query CDATA #IMPLIED
        update CDATA #IMPLIED
>
]>
<data>
"""
ucmUpdates.write(header)
xmldoc = minidom.parseString(lookup.read().strip())
for row in xmldoc.getElementsByTagName("row"):
    npUpd=""
    dnUpd=""
    dn=""
    name=""
    npSql=""
    dnSql=""
    
    for node in row.childNodes:
    
        if node.nodeName == "numplan_pkid":
            npUpd=node.childNodes.item(0).nodeValue
            npSql="<sql update=\"update numplan set tkautoanswer=1 where pkid='"+npUpd+"'\"/>"
            ucmUpdates.write(npSql)
        elif node.nodeName == "devicenumplanmap_pkid":
            dnUpd=node.childNodes.item(0).nodeValue
            dnSql="<sql update=\"update devicenumplanmap set fkcallingsearchspace_monitoring='f3954bc8-fd6f-f059-e1fd-ffd8f321b1a8' where pkid='"+dnUpd+"'\"/>"
            ucmUpdates.write(dnSql)
        elif node.nodeName == "name":
            name=node.childNodes.item(0).nodeValue            
        elif node.nodeName == "dn": 
            dn=node.childNodes.item(0).nodeValue
            break

    print name+"["+dn+"]: forcing auto answer"
    print "\t npUpd="+npUpd
    print "\t npSql="+npSql
    print "\t dnUpd="+dnUpd
    print "\t dnSql="+dnSql

ucmUpdates.write("</data>")
ucmUpdates.close();
lookup.close()